name: Nodejs CI

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install and run tests in headless mode
        run: |
          npm install
          npm run headless